namespace CIG
{
	public enum MultiplierType
	{
		ExpansionCashCost,
		ResidentialCashCost,
		ResidentialGoldCost,
		CommercialCashCost,
		CommercialGoldCost,
		DecorationCashCost,
		DecorationsGoldCost,
		CommunityCashCost,
		CommunityGoldCost,
		ResidentialInstantGoldCostBuilding,
		CommercialInstantGoldCostBuilding,
		CommunityInstantGoldCostBuilding,
		ResidentialInstantGoldCostUpgrade,
		CommercialInstantGoldCostUpgrade,
		CommunityInstantGoldCostUpgrade,
		ResidentialCashCostUpgrade,
		CommercialCashCostUpgrade,
		CommunityCashCostUpgrade,
		KeyDealGoldKeyCost,
		KeyDealSilverKeyCost,
		LandmarksGoldKeyCost,
		LandmarksSilverKeyCost,
		UpgradeGoldKeyReward,
		UpgradeSilverKeyReward,
		LevelUpCashReward,
		UpspeedGoldCost,
		CommercialBuildingProfit,
		XP
	}
}
