using System.Collections.Generic;

namespace CIG
{
	[BalancePropertyClass("ongoingQuest", false)]
	[BalanceEquallySizedProperties(new string[]
	{
		"predefinedTargets",
		"predefinedRewards"
	})]
	public class OngoingQuestProperties : QuestProperties
	{
		private const string PredefinedTargetsKey = "predefinedTargets";

		private const string AutoGeneratedTargetStepKey = "autoGeneratedTargetStep";

		private const string PredefinedRewardsKey = "predefinedRewards";

		private const string AutoGeneratedRewardKey = "autoGeneratedReward";

		[BalanceProperty("predefinedTargets")]
		public List<int> PredefinedTargets
		{
			get;
			private set;
		}

		[BalanceProperty("autoGeneratedTargetStep")]
		public int AutoGeneratedTargetStep
		{
			get;
			private set;
		}

		[BalanceProperty("predefinedRewards")]
		public List<Currencies> PredefinedRewards
		{
			get;
			private set;
		}

		[BalanceProperty("autoGeneratedReward")]
		public Currencies AutoGeneratedReward
		{
			get;
			private set;
		}

		public OngoingQuestProperties(PropertiesDictionary propsDict, string baseKey)
			: base(propsDict, baseKey)
		{
			PredefinedTargets = GetProperty("predefinedTargets", new List<int>());
			AutoGeneratedTargetStep = GetProperty("autoGeneratedTargetStep", 0);
			PredefinedRewards = GetProperty("predefinedRewards", new List<Currencies>());
			AutoGeneratedReward = GetProperty("autoGeneratedReward", new Currencies());
		}
	}
}
