namespace CIG
{
	public class OngoingQuestTarget : QuestTarget
	{
		private readonly OngoingQuestProperties _properties;

		private bool _completed;

		private int _targetIndex;

		private long _targetAmount;

		private Currencies _reward;

		private const string TargetIndexKey = "TargetIndex";

		public override long TargetAmount => _targetAmount;

		public override Currencies Reward => _reward;

		public override bool Completed => _completed;

		public OngoingQuestTarget(StorageDictionary storage, OngoingQuestProperties properties)
		{
			_properties = properties;
			_targetIndex = storage.Get("TargetIndex", 0);
			UpdateTarget();
		}

		public override Currencies Collect()
		{
			Currencies reward = Reward;
			_targetIndex++;
			UpdateTarget();
			return reward;
		}

		private void UpdateTarget()
		{
			bool flag = UpdateTargetAmount();
			bool flag2 = UpdateReward();
			_completed = (!flag || !flag2);
		}

		private bool UpdateTargetAmount()
		{
			if (_targetIndex >= 0 && _targetIndex < _properties.PredefinedTargets.Count)
			{
				_targetAmount = _properties.PredefinedTargets[_targetIndex];
				return true;
			}
			long num = _properties.PredefinedTargets[_properties.PredefinedTargets.Count - 1];
			if (_properties.AutoGeneratedTargetStep > 0)
			{
				_targetAmount = num + (_targetIndex - _properties.PredefinedTargets.Count + 1) * _properties.AutoGeneratedTargetStep;
				return true;
			}
			_targetAmount = num;
			return false;
		}

		private bool UpdateReward()
		{
			if (_targetIndex >= 0 && _targetIndex < _properties.PredefinedRewards.Count)
			{
				_reward = _properties.PredefinedRewards[_targetIndex];
				return true;
			}
			if (_properties.AutoGeneratedReward != new Currencies())
			{
				_reward = _properties.AutoGeneratedReward;
				return true;
			}
			_reward = _properties.PredefinedRewards[_properties.PredefinedRewards.Count - 1];
			return false;
		}

		public override StorageDictionary Serialize()
		{
			StorageDictionary storageDictionary = base.Serialize();
			storageDictionary.Set("TargetIndex", _targetIndex);
			return storageDictionary;
		}
	}
}
